### PR TITLE
Bug fix for fire emissions

### PR DESCRIPTION
**Pull request by fvitt**
This fixes an issue with how coefficients are applied to individual fire components.  This requires a change to CTSM code.

### CODE REVIEW

**Comment by ekluzek** [comment]
Can this change come into main? We need this for a CTSM PR https://github.com/ESCOMP/CTSM/pull/1532

**Comment by ekluzek** [comment]
@fischer-ncar could you approve this to come to main?

**Comment by ekluzek** [comment]
It looks like this PR, the one for CESM, and the one for CTSM need to be done at the same time. @fvitt am I understanding that correctly? Are there any other components that need to be coordinated with this? CAM maybe?

**Comment by ekluzek** [comment]
OK, actually this is the change for the MCT coupler, the CESM change is separate from this. I would say that we should drop this change, but that would mean that MCT would no longer even compile. So I think we still need to do all of these. Since, this requires coordination of several CESM component tags I think we should coordinate it in a CESM alpha tag.

**Comment by mvertens** [comment]
@fvitt - does not nuopc fire emission code have a corresponding fix. I think its important to ensure that if a fix is needed for mct it must also be fixed in nuopc if that is the case.

**Comment by ekluzek** [comment]
@mvertens yes, the NUOPC fix is in https://github.com/ESCOMP/CESM_share/pull/13

**Comment by mvertens** [comment]
@ekluzek - thanks for confirming.

**Comment by fvitt** [comment]
> It looks like this PR, the one for CESM, and the one for CTSM need to be done at the same time. @fvitt am I understanding that correctly? Are there any other components that need to be coordinated with this? CAM maybe?

There are related changes for CAM.  See https://github.com/ESCOMP/CAM/pull/452.  Technically, the CAM changes are independent and can go in anytime.

**Review by fischer-ncar — APPROVED** [review]

**Comment by ekluzek** [comment]
@fischer-ncar can you bring this PR in so that we can start working on the CESM fire-emission tag?

**Pull request merged**
